Rename HMT values in the profile, get active balance from node
humanprotocol/human-app pull request #107
Opened 2022-05-13 11:24 UTC by makarofalex3

https://app.asana.com/0/1202223693300501/1202116150158266

Renamed "Total HMT earned" to "Referral HMT Earned"
Rename "Available HMT to withdraw" to "HMT available to withdraw"
Replaced "HMT Pending" and add a "Wallet HMT Balance". 
Added call to a blockchain node to check balance of the HMT

additionally added .eslintignore to fix husky validation error in abi json 
before:
![image](https://user-images.githubusercontent.com/105057348/168273407-5eb6d1c3-e7b2-490c-b469-0764aa93bf94.png)

after:
![image](https://user-images.githubusercontent.com/105057348/168272340-1bcb52c8-2901-4dde-9caa-0a970d1c24f3.png)

2022-05-13 12:44 UTC, AmrEssamSh requested changes
Please move `abi` directory out of `src` and rename it to `artifacts`

2022-05-13 12:44 UTC, AmrEssamSh commented on src/hooks/useContractAbi.js
> +        const provider = new ethers.providers.Web3Provider(window.ethereum);
Please use Infura as a provider, we are working on the Polygon mainnet.

2022-05-13 12:44 UTC, AmrEssamSh commented on src/hooks/useContractAbi.js
> +        const token = new ethers.Contract(walletAddress, HMTokenABI);
You need to pass in the the human token contract address not the wallet address

2022-05-13 12:44 UTC, AmrEssamSh commented on src/hooks/useContractAbi.js
> +    contract,
Why returning `contract`?

2022-05-13 14:27 UTC, Dzeranov commented on src/hooks/useContractAbi.js
> +        const balanceBigNumber = await provider.getBalance(walletAddress);
You need to make here a call like
`const hmtBalance = await token.methods.balanceOf(walletAddress).call();`
Otherwise you'll get a balance in MATIC not in HMT.

2022-05-13 14:29 UTC, Dzeranov commented on src/hooks/useContractAbi.js
> +        const tokenBalance = Number(balanceBigNumber);
This number will have a lot of zeros. So you need to handle it not with Number but with BigInt for example.
And then show a readable version of balance.
4 HMT instead of 4000000000000000000

2022-05-14 13:39 UTC, makarofalex3 commented on package.json
> +    "ethers": "^5.6.5",
fixed

2022-05-14 13:39 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +        const provider = new ethers.providers.Web3Provider(window.ethereum);
fixed

2022-05-14 13:39 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +        const token = new ethers.Contract(walletAddress, HMTokenABI);
fixed

2022-05-14 13:39 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +    contract,
right, we dont need, fixed

2022-05-14 13:39 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +        const balanceBigNumber = await provider.getBalance(walletAddress);
fixed

2022-05-14 13:40 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +        const tokenBalance = Number(balanceBigNumber);
fixed

2022-05-14 13:52 UTC, Dzeranov commented
> Please move `abi` directory out of `src` and rename it to `artifacts`

Please, do this.

2022-05-14 13:53 UTC, Dzeranov commented on src/hooks/useContractAbi.js
> +const HUMAN_HMT_TOKEN_CONTRACT_ADDRESS = '0x444c45937D2202118a0FF9c48d491cef527b59dF';
Try not to hardcode any variables like this, pass it as env.

2022-05-14 19:37 UTC, makarofalex3 commented on src/hooks/useContractAbi.js
> +const HUMAN_HMT_TOKEN_CONTRACT_ADDRESS = '0x444c45937D2202118a0FF9c48d491cef527b59dF';
fixed

2022-05-14 19:40 UTC, makarofalex3 commented on src/pages/Workspace/user-stats.jsx
> +  balance: PropTypes.number,
fixed

2022-05-14 19:41 UTC, makarofalex3 commented on src/pages/Workspace/user-stats.jsx
> +  balance: 0,
fixed

2022-05-16 14:50 UTC, AmrEssamSh commented
Please add new env variables to `.env.example` & `README.md`

2022-05-16 14:58 UTC, AmrEssamSh commented on src/hooks/useContractAbi.js
> +const tokenArrd = process.env.REACT_APP_HUMAN_HMT_TOKEN_CONTRACT_ADDRESS;
typo in `tokenArrd `

2022-05-16 18:19 UTC, AmrEssamSh commented
> Please add new env variables to `.env.example` & `README.md`

please add to `.env.example` also

2022-05-17 07:15 UTC, AmrEssamSh approved these changes

2022-05-17 08:17 UTC, Dzeranov approved these changes

2022-05-17 08:45 UTC, merged