added env vars runtime config
humanprotocol/human-app pull request #156
Opened 2022-05-31 11:02 UTC by makarofalex3

Added env vars runtime config in FE part, need update BE and CI/CD part

from this step:  https://github.com/kunokdev/cra-runtime-environment-variables#-production

2022-05-31 12:12 UTC, Dzeranov commented
Please, update `README`.
And why do we need to update BE part?

2022-05-31 14:52 UTC, Dzeranov commented on package.json
>      "start-prod": "node server.js",
We need to change `start-prod` command too.

2022-06-07 13:48 UTC, makarofalex3 commented
@ivhus

2022-06-07 15:40 UTC, ivhus requested changes
Chechking on the topic found this documentation https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs 

This approach by the link is what's needed

2022-06-21 10:51 UTC, closed without merging