UI bugs
humanprotocol/human-app pull request #24
Opened 2021-10-12 16:27 UTC by cleandevcode

UI fixes and improvements

- Fixed spacing issue: Space is missed in various parts in the app
![image (1)](https://user-images.githubusercontent.com/52365167/137001572-ec623426-372d-4ec1-a70d-3b36a23f9006.png)

- Fixed centering issue: Spacing on CTA text is inconsistent
![image](https://user-images.githubusercontent.com/52365167/137001706-ef719649-8698-4496-b248-e490d7daaaaa.png)

- Fixed routing issue: Icon should always take the user back to the homepage. Right now, on the HUMAN App page (top left), it redirects to the same page.
![image (4)](https://user-images.githubusercontent.com/52365167/137001597-dcabc244-78c5-41fb-bf32-c71a7a1f0ef4.png)

2021-10-12 17:24 UTC, vkomodey requested changes

2021-10-12 17:24 UTC, vkomodey commented on src/App.scss
> +        color: white!important;
the same about `!important` statement here. try to avoid

2021-10-12 17:24 UTC, vkomodey commented on src/components/inputs/url.jsx
> +  // };
don't leave comments that are unnecessary in your code. we have git history

2021-10-12 17:24 UTC, vkomodey commented on src/components/inputs/url.jsx
> +        </div> */}
the same about dead code

2021-10-12 17:24 UTC, vkomodey commented on src/components/scrollToTop/ScrollToTop.jsx
> +    // eslint-disable-next-line no-undef
You can tell eslint [that your env is browser](https://stackoverflow.com/questions/30398825/eslint-window-is-not-defined-how-to-allow-global-variables-in-package-json). So you won't have to put these disable comments for every built-in usage.

2021-10-12 17:24 UTC, vkomodey commented on src/pages/Job/job.jsx
> +                  {/* <i className="material-icons text-white">share</i> */}
remove

2021-10-12 17:24 UTC, vkomodey commented on src/pages/Login/register.jsx
> +                  onClick={() => history.push('/')}
Why have you changed this to constant string? "Routes.Home.path" is a good variable, because we can change the home path and would not have to change it across the app

2021-10-12 17:24 UTC, vkomodey commented on src/components/scrollToTop/ScrollToTop.jsx
> +  }, [location]);
Why are you listening to location changes here?

2021-10-13 00:52 UTC, cleandevcode commented on src/components/scrollToTop/ScrollToTop.jsx
> +  }, [location]);
It scrolls up to the top.

2021-10-14 12:00 UTC, cleandevcode commented on src/pages/Job/job.jsx
> +                  {/* <i className="material-icons text-white">share</i> */}
removed

2021-10-14 12:00 UTC, cleandevcode commented on src/components/inputs/url.jsx
> +  // };
removed

2021-10-14 14:05 UTC, vkomodey commented on src/components/inputs/url.jsx
> +  // reset: PropTypes.func.isRequired,
remove

2021-10-14 14:06 UTC, vkomodey commented on src/pages/Job/job.jsx
> +                  {/* <i className="material-icons text-white">share</i> */}
no, it's not

2021-10-14 14:08 UTC, vkomodey commented on src/pages/Profile/profile.jsx
> +                  onClick={() => history.push('/')}
still see '/' here. use the constant

2021-10-14 14:08 UTC, vkomodey commented on src/pages/Login/login.jsx
> +            <Button className="form-control btn mr-2 bg-white" onClick={() => history.push('/')}>
still see '/' here. use the constant

2021-10-14 20:33 UTC, cleandevcode commented on src/components/inputs/url.jsx
> +  // reset: PropTypes.func.isRequired,
removed

2021-10-15 11:38 UTC, cleandevcode commented on public/css/style.scss
> +  border: 2px solid #6309ff!important;
Updated

2021-10-15 15:18 UTC, merged