Suspend/unsuspend users widgets added to admin panel
humanprotocol/human-app pull request #58
Opened 2022-01-27 09:18 UTC by Dzeranov

2022-01-27 10:24 UTC, vkomodey requested changes

2022-01-27 10:24 UTC, vkomodey commented on src/pages/Workspace/admin-panel/suspend-users.jsx
> +              <TextField
let's add a hint, on how to use this text field. I mean, right now it is impossible to understand that this input accepts multiple emails at once

the same for unsuspend action

2022-01-27 10:24 UTC, vkomodey commented on src/pages/Workspace/admin-panel/suspend-users.jsx
> +/* eslint-disable no-unused-vars */
delete the line and don't use 'unused vars'

2022-01-27 10:25 UTC, Dzeranov commented on src/pages/Workspace/admin-panel/suspend-users.jsx
> +              <TextField
Sure.

2022-01-27 10:25 UTC, Dzeranov commented on src/pages/Workspace/admin-panel/suspend-users.jsx
> +/* eslint-disable no-unused-vars */
Not using, this line was added unintetionally.

2022-01-28 13:00 UTC, vkomodey approved these changes

2022-01-28 13:02 UTC, merged