Notification about cookies added
humanprotocol/human-app pull request #68
Opened 2022-03-03 14:36 UTC by Dzeranov

Cookies notification added.
Expiration time is 30 days.
https://app.asana.com/0/1200854944775310/1201707522540591

2022-03-04 11:06 UTC, vkomodey commented
Could you please show how is it look like?

2022-03-04 12:21 UTC, Dzeranov commented
> Could you please show how is it look like?

![image](https://user-images.githubusercontent.com/20276898/156762564-438e7ce1-7bc7-493d-9153-9d7580439935.png)

2022-03-16 11:07 UTC, vkomodey commented
please be careful. the target branch should be master

2022-03-16 11:15 UTC, vkomodey requested changes
All good. Last thing about privacy policy href and we are gtg

2022-03-16 11:15 UTC, vkomodey commented on src/App.jsx
> +          <a href="https://humanprotocol.org/app/privacy-policy" style={{ fontSize: '14px' }}>
For a better UX please add attributes `target="_blank"` and `rel="noreferrer noopener"` for opening the privacy policy in the new page

2022-03-16 12:55 UTC, merged