Fix CI
humanprotocol/human-app pull request #74
Opened 2022-03-09 20:28 UTC by ivhus

2022-03-10 17:24 UTC, vkomodey requested changes

2022-03-10 17:24 UTC, vkomodey commented on .github/workflows/docker_build.yml
> +        docker build -f Dockerfile .
build phase for the human app should include build arguments:

```
REACT_APP_API_URL
REACT_APP_HCAPTCHA_SITE_KEY
REACT_APP_CIVIC_APP_ID
```

2022-03-10 17:24 UTC, vkomodey commented on .github/workflows/docker_build.yml
> +      if: github.event_name != 'pull_request'
not sure I understand this. so if ANY event happened except pull request - we should trigger the build phase?

2022-03-13 19:00 UTC, ivhus commented on .github/workflows/docker_build.yml
> +        docker build -f Dockerfile .
build arguments added

2022-03-13 19:04 UTC, ivhus commented on .github/workflows/docker_build.yml
> +      if: github.event_name != 'pull_request'
This is necessary for docker push does not run on pull request (there are 2 steps in the pipeline with docker build command, but docker push is run only for the develop and master branches)

2022-03-16 11:06 UTC, merged