Check if token is expired on an initial load
humanprotocol/human-app pull request #92
Opened 2022-04-11 13:56 UTC by Dzeranov

https://app.asana.com/0/1200854944775310/1201861194926450

2022-04-11 14:46 UTC, AmrEssamSh requested changes

2022-04-11 14:46 UTC, AmrEssamSh commented on src/utils/jwt.js
> +  console.log(exp * 1000);
Please remove console.log

2022-04-12 14:48 UTC, AmrEssamSh commented on src/index.jsx
>        notifier.error(err.message);
I think we need to add a generic error message to the user like 'Something went wrong, please try again', Instead of throwing the low level error message.

For example: if there was an error decoding the token; user will get "Invalid token specified: Cannot read properties of undefined (reading 'replace')"

2022-04-13 10:21 UTC, vkomodey commented on src/index.jsx
>        notifier.error(err.message);
I think it is a better idea to not show any error at all. This is a pre-check, when app is loaded. In case of any error he will see a first home screen where he should able to login after

The error like "Something went wrong, please try again" says anything what user should try, because he just loaded the app first time. He did not perform any actions at all

2022-04-13 10:54 UTC, Dzeranov commented on src/index.jsx
>        notifier.error(err.message);
I think that the best approach here is just to remove this 
 `notifier.error(err.message);`

2022-04-22 09:25 UTC, vkomodey commented
@AmrEssamSh what's you decision here?

2022-04-22 10:46 UTC, AmrEssamSh approved these changes

2022-04-22 11:23 UTC, merged